language: ruby
rvm:
  - 2.1.3
services:
  - postgresql
  - redis
env:
  - RAILS_ENV=test
before_script:
  - bundle exec rake db:create db:schema:load
script:
  - bundle exec rspec spec
addons:
  postgresql: "9.3"
