language: ruby
rvm:
  - 2.1.3
services:
  - postgresql
  - redis-server
env:
  - RAILS_ENV=test
before_script:
  - bundle config build.nokogiri --use-system-libraries
  - bundle exec rake db:create db:schema:load
script:
  - RAILS_ENV=test bundle exec rspec spec
addons:
  postgresql: "9.3"
