language: ruby
rvm:
  - 2.1.3
services:
  - postgresql
  - redis-server
  - memcached
env:
  - RAILS_ENV=test
before_install:
  - bundle config build.nokogiri --use-system-libraries
before_script:
  - bundle exec rake db:create db:structure:load
script:
  - bundle exec rspec spec
addons:
  postgresql: "9.3"
